remote_theme: "jekyll/minima@1e8a445"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

minima:
  hide_site_feed_link: true  # `false` or `null` by default

#remote_theme: pages-themes/tactile@v0.2.0  
#title: [Midwest Programming Languages Summit - 2025]
#description: [MWPLS - 2025 at the University of Minnesota]
